name: Python CI/CD

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo apt-get install -y chromium-chromedriver
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download and install ChromeDriver
        run: |
          CHROMEDRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d ~/bin
          echo "##[add-path]${{ runner.workspace }}/bin" # Add chromedriver directory to PATH
          chmod +x ~/bin/chromedriver

      - name: Run tests
        run: |
          pytest main.py

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: результати/
