name: Python CI/CD

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Chrome version
        run: echo "google-chrome-stable google-chrome-stable/version select 113.0.5672.24-1" | sudo debconf-set-selections

      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable


      - name: Run tests
        run: |
          pytest main.py

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: результати/
